# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :setup do   
    cocoapods(
      clean_install: true,     
      repo_update: true,
      use_bundle_exec: false
    )
  end

  desc "Run SwiftLint to check code quality"
  lane :swiftlintCheck do
     swiftlint(
      strict: false,              # Fail on any SwiftLint issues
      output_file: "swiftlint_report.txt",  # Optional:Output lint report to a file
      ignore_exit_status: false   # Exit with an error if there are violations
    )
 end

 desc "Build app"
 lane :build do
 build_app(
  workspace: "ObjectiveCProject.xcworkspace",
  scheme: "ObjectiveCProject",
  skip_build_archive: true,
  skip_archive: true,
  clean: true
)
increment_build_number
 end

desc "Run all tasks"
  lane :all do
    setup       # Calls the setup lane
    swiftlintCheck   # Calls the swiftlint lane
    build
  end	
end
